import type { Metadata } from 'next'
import '../core/globals.css'
import { Raleway } from 'next/font/google'
import { CardContainer } from '@/components/card/CardContainer'
import { Navbar } from '@/components/Navbar/Navbar'
import { Footer } from '@/components/Footer/Footer'
import { WebVitals } from './web-vitals'

const raleway = Raleway({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} antialiased bg-[#232946]`}>
        <CardContainer>
          <Navbar />
          {children}
          <Footer />
        </CardContainer>
        <WebVitals />
      </body>
    </html>
  )
}
